// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  developerSidebar: [
    'intro',
    'ecosystem',
    {
      type: 'category',
      label: 'Diagram gallery',
      link: { type: 'doc', id: 'diagrams/index' },
      items: [
        'diagrams/ecosystem',
        'diagrams/sd-main-system',
        'diagrams/sd-main-features',
        'diagrams/sd-cs',
        'diagrams/sd-billing',
        'diagrams/data',
        'diagrams/workflows',
      ],
    },

    // ─── 1. sd-main · Dealer CRM ───────────────────────────────
    {
      type: 'category',
      label: 'sd-main · Dealer CRM',
      link: { type: 'doc', id: 'sd-main/overview' },
      items: [
        {
          type: 'category',
          label: 'System Architecture',
          key: 'sd-main-system-architecture',
          items: [
            'architecture/overview',
            'architecture/tech-stack',
            'architecture/multi-tenancy',
            'architecture/caching',
            'architecture/jobs-and-scheduling',
            'project/structure',
            'project/configuration',
            'project/conventions',
            'project/local-setup',
            'project/docker',
            'security/auth-and-roles',
            'security/rbac',
            'security/sessions',
            'security/data-isolation',
            'security/sd-main-landmines',
            'architecture/diagram-conventions',
            'devops/deployment',
            'devops/docker-compose',
            'devops/nginx',
            'devops/monitoring-logging',
            'devops/backup-and-restore',
            'devops/scaling',
          ],
        },
        {
          type: 'category',
          label: 'Workflows',
          key: 'sd-main-workflows',
          items: [
            'modules/overview',
            'modules/orders',
            'modules/clients',
            'modules/agents',
            'modules/warehouse',
            'modules/inventory',
            'modules/stock',
            'modules/store',
            'modules/finans',
            'modules/payment',
            'modules/audit-adt',
            'modules/gps',
            'modules/integration',
            'modules/onlineOrder',
            'modules/sms',
            'modules/dashboard',
            'modules/report',
            'modules/settings-access-staff',
            'modules/sync',
            'api/overview',
            'api/authentication',
            'api/api-v1',
            'api/api-v2',
            'api/api-v3-mobile',
            'api/api-v4-online',
            'api/error-codes',
            'api/webhooks',
            'integrations/overview',
            'integrations/1c-esale',
            'integrations/didox',
            'integrations/faktura-uz',
            'integrations/smartup',
            'integrations/telegram',
            'integrations/fcm',
            'integrations/sms',
            'integrations/gps',
            'frontend/overview',
            'frontend/getting-started',
            'frontend/conventions',
            'frontend/adding-a-screen',
            'frontend/yii-views',
            'frontend/jquery-patterns',
            'frontend/js-plugins',
            'frontend/ng-modules',
            'frontend/assets-pipeline',
            'ui/wireframes',
            'ui/component-catalog',
            'ui/build-a-page',
            'ui/page-layout',
            'ui/filters',
            'ui/tables',
            'ui/forms',
            'ui/modals',
          ],
        },
        {
          type: 'category',
          label: 'Data Schemes',
          key: 'sd-main-data-schemes',
          items: [
            'data/overview',
            'data/erd',
            'data/erd-real',
            'data/schema-reference',
            'data/core-entities',
            'data/diagrams-paste-ready',
            'data/conventions',
            'data/migrations',
          ],
        },
      ],
    },

    // ─── 2. sd-cs · HQ Country Sales ───────────────────────────
    {
      type: 'category',
      label: 'sd-cs · HQ Country Sales',
      link: { type: 'doc', id: 'sd-cs/overview' },
      items: [
        {
          type: 'category',
          label: 'System Architecture',
          key: 'sd-cs-system-architecture',
          items: [
            'sd-cs/architecture',
            'sd-cs/multi-db',
            'sd-cs/local-setup',
            'sd-cs/sd-components',
          ],
        },
        {
          type: 'category',
          label: 'Workflows',
          key: 'sd-cs-workflows',
          items: [
            'sd-cs/modules',
            'sd-cs/sd-main-integration',
            'sd-cs/reports-pivots',
          ],
        },
        {
          type: 'category',
          label: 'Data Schemes',
          key: 'sd-cs-data-schemes',
          items: [
            'sd-cs/data-schemes',
          ],
        },
      ],
    },

    // ─── 3. sd-billing · Subscriptions & licensing ─────────────
    {
      type: 'category',
      label: 'sd-billing · Subscriptions',
      link: { type: 'doc', id: 'sd-billing/overview' },
      items: [
        {
          type: 'category',
          label: 'System Architecture',
          key: 'sd-billing-system-architecture',
          items: [
            'sd-billing/modules',
            'sd-billing/auth-and-access',
            'sd-billing/local-setup',
            'sd-billing/security-landmines',
          ],
        },
        {
          type: 'category',
          label: 'Workflows',
          key: 'sd-billing-workflows',
          items: [
            'sd-billing/subscription-flow',
            'sd-billing/cron-and-settlement',
            'sd-billing/payment-gateways',
            'sd-billing/integration',
          ],
        },
        {
          type: 'category',
          label: 'Data Schemes',
          key: 'sd-billing-data-schemes',
          items: [
            'sd-billing/domain-model',
          ],
        },
      ],
    },

    // ─── Cross-cutting reference ───────────────────────────────
    {
      type: 'category',
      label: 'Reference & cross-cutting',
      key: 'reference-cross-cutting',
      items: [
        'architecture/diagrams',
        'security/overview',
        'team/index',
        'team/onboarding',
        'team/qa',
        'team/pm',
        'team/workflow-design',
        'team/rag-indexing',
        'quality/testing',
        'quality/coding-standards',
        'quality/contribution',
        'quality/release-process',
        'adr/index',
        'adr/yii1-stay',
        'adr/multi-tenant-db-per-customer',
        'adr/redis-three-databases',
        'adr/api-versioning',
        'billing/overview',
        'diagrams-inventory',
      ],
    },

    'troubleshooting',
    'changelog',
  ],
};

module.exports = sidebars;
