// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  developerSidebar: [
    'intro',
    'ecosystem',
    {
      type: 'category',
      label: 'Team (onboarding · QA · PM)',
      items: [
        'team/index',
        'team/onboarding',
        'team/qa',
        'team/pm',
      ],
    },
    {
      type: 'category',
      label: 'sd-billing (subscriptions)',
      items: [
        'sd-billing/overview',
        'sd-billing/domain-model',
        'sd-billing/modules',
        'sd-billing/payment-gateways',
        'sd-billing/subscription-flow',
        'sd-billing/cron-and-settlement',
        'sd-billing/auth-and-access',
        'sd-billing/local-setup',
        'sd-billing/security-landmines',
        'sd-billing/integration',
      ],
    },
    {
      type: 'category',
      label: 'Billing in sd-main (integration)',
      items: [
        'billing/overview',
        'billing/integration',
      ],
    },
    {
      type: 'category',
      label: 'sd-cs (HQ)',
      items: [
        'sd-cs/overview',
        'sd-cs/multi-db',
        'sd-cs/sd-main-integration',
        'sd-cs/modules',
        'sd-cs/reports-pivots',
        'sd-cs/local-setup',
        'sd-cs/sd-components',
      ],
    },
    {
      type: 'category',
      label: 'Architecture',
      items: [
        'architecture/overview',
        'architecture/tech-stack',
        'architecture/multi-tenancy',
        'architecture/caching',
        'architecture/jobs-and-scheduling',
        'architecture/diagrams',
      ],
    },
    {
      type: 'category',
      label: 'Project',
      items: [
        'project/structure',
        'project/conventions',
        'project/local-setup',
        'project/docker',
        'project/configuration',
      ],
    },
    {
      type: 'category',
      label: 'Modules',
      items: [
        'modules/overview',
        'modules/orders',
        'modules/clients',
        'modules/agents',
        'modules/warehouse',
        'modules/inventory',
        'modules/stock',
        'modules/store',
        'modules/finans',
        'modules/payment',
        'modules/audit-adt',
        'modules/gps',
        'modules/integration',
        'modules/onlineOrder',
        'modules/sms',
        'modules/dashboard',
        'modules/report',
        'modules/settings-access-staff',
        'modules/sync',
      ],
    },
    {
      type: 'category',
      label: 'Data Model',
      items: [
        'data/overview',
        'data/erd',
        'data/core-entities',
        'data/conventions',
        'data/migrations',
      ],
    },
    {
      type: 'category',
      label: 'API Reference',
      items: [
        'api/overview',
        'api/authentication',
        'api/api-v1',
        'api/api-v2',
        'api/api-v3-mobile',
        'api/api-v4-online',
        'api/error-codes',
        'api/webhooks',
      ],
    },
    {
      type: 'category',
      label: 'Frontend',
      items: [
        'frontend/overview',
        'frontend/yii-views',
        'frontend/js-plugins',
        'frontend/ng-modules',
        'frontend/assets-pipeline',
      ],
    },
    {
      type: 'category',
      label: 'UI Wireframes',
      items: [
        'ui/wireframes',
        'ui/page-layout',
        'ui/filters',
        'ui/tables',
        'ui/forms',
        'ui/modals',
      ],
    },
    {
      type: 'category',
      label: 'Integrations',
      items: [
        'integrations/overview',
        'integrations/1c-esale',
        'integrations/didox',
        'integrations/faktura-uz',
        'integrations/smartup',
        'integrations/telegram',
        'integrations/fcm',
        'integrations/sms',
        'integrations/gps',
      ],
    },
    {
      type: 'category',
      label: 'Security',
      items: [
        'security/overview',
        'security/auth-and-roles',
        'security/rbac',
        'security/sessions',
        'security/data-isolation',
      ],
    },
    {
      type: 'category',
      label: 'DevOps',
      items: [
        'devops/deployment',
        'devops/docker-compose',
        'devops/nginx',
        'devops/monitoring-logging',
        'devops/backup-and-restore',
        'devops/scaling',
      ],
    },
    {
      type: 'category',
      label: 'Quality',
      items: [
        'quality/testing',
        'quality/coding-standards',
        'quality/contribution',
        'quality/release-process',
      ],
    },
    {
      type: 'category',
      label: 'ADRs',
      items: [
        'adr/index',
        'adr/yii1-stay',
        'adr/multi-tenant-db-per-customer',
        'adr/redis-three-databases',
        'adr/api-versioning',
      ],
    },
    'troubleshooting',
    'changelog',
  ],
};

module.exports = sidebars;
